### ISSUE TITLE
Mapping file "META-INF/Taskorm.xml" cannot be resolved.

### ISSUE THREAD

**Issue by TobinFrost** [jeetemplates/jbpm6#1]
Hi,
I can't found  : META-INF/Taskorm.xml , META-INF/JBPMorm.xml, META-INF/Servicesorm.xml, META-INF/TaskAuditorm.xml and i don't know why.
I'm using eclipse neon2 and maven 3.

i'm newbie in jBPM6 , can you explain me please.

**Comment by paoesco** [comment]
Hi @TobinFrost ,

these files are in jbpm jar files.

- Taskorm.xml is in jbpm-human-task-core-***.jar 
- JBPMorm.xml is in jbpm-persistence-jpa-***.jar
- Servicesorm.xml is in droolsjbpm-knowledge-services-***.jar
- etc
(*** is the version).

If your project is setup properly with Maven pulling dependencies, they should be in the classpath of your war and so it should see them.

Try to see if you have your classpath and all dependencies set correctly.

**Comment by TobinFrost** [comment]
i have both jar files jbpm-human-task-jpa and  jbpm-persistence-jpa in my Maven Dependencies but the problem persists, i don't know why.

**Comment by paoesco** [comment]
I tried to install the application again and it's working well.

Have you checked your Java version ? It's Java 7 only

**Comment by paoesco** [comment]
@TobinFrost can you share your stack trace ? or error ?
Thanks

**Comment by paoesco** [comment]
Hi @TobinFrost ,

Have you tried to run the war ?

Maybe it's only an Eclipse error : https://www.eclipse.org/forums/index.php/t/1067598/

IDE sometimes can complain about missing files but runtime is good.

**Comment by TobinFrost** [comment]
Sorry man !
It's was my fault!

**Comment by paoesco** [comment]
Glad that it works !
